"""ELM model definitions.

Pydantic models for ELM (Expression Logical Model) structures including:
- Library structure (identifier, usings, statements)
- Expression nodes (literals, operators, queries, etc.)
- Type specifiers
"""

from fhirkit.engine.elm.models.expressions import (
    ELMAbs,
    # Arithmetic
    ELMAdd,
    ELMAfter,
    ELMAggregateClause,
    ELMAggregateExpression,
    # Query
    ELMAliasedQuerySource,
    ELMAliasRef,
    ELMAllTrue,
    # Boolean
    ELMAnd,
    ELMAnyTrue,
    # Type operations
    ELMAs,
    ELMAvg,
    ELMBefore,
    ELMBinaryExpression,
    ELMCalculateAge,
    ELMCalculateAgeAt,
    ELMCase,
    ELMCaseItem,
    ELMCeiling,
    ELMCoalesce,
    ELMCode,
    ELMCodeRef,
    ELMCodeSystemRef,
    ELMCollapse,
    ELMCombine,
    # String
    ELMConcatenate,
    ELMConcept,
    ELMConceptRef,
    ELMContains,
    ELMConvertsToBoolean,
    ELMConvertsToDate,
    ELMConvertsToDateTime,
    ELMConvertsToDecimal,
    ELMConvertsToInteger,
    ELMConvertsToQuantity,
    ELMConvertsToString,
    ELMConvertsToTime,
    # Aggregates
    ELMCount,
    ELMDate,
    ELMDateFrom,
    ELMDateTime,
    ELMDateTimeComponentFrom,
    ELMDifferenceBetween,
    ELMDistinct,
    ELMDivide,
    ELMDurationBetween,
    ELMEnd,
    ELMEnds,
    ELMEndsWith,
    # Comparison
    ELMEqual,
    ELMEquivalent,
    ELMExcept,
    ELMExists,
    ELMExp,
    ELMExpand,
    # Base
    ELMExpression,
    # References
    ELMExpressionRef,
    ELMFilter,
    # Collections
    ELMFirst,
    ELMFlatten,
    ELMFloor,
    ELMForEach,
    ELMFunctionRef,
    ELMGeometricMean,
    ELMGreater,
    ELMGreaterOrEqual,
    ELMIdentifierRef,
    # Control flow
    ELMIf,
    ELMImplies,
    ELMIn,
    ELMIncludedIn,
    ELMIncludes,
    ELMInCodeSystem,
    ELMIndexer,
    ELMIndexOf,
    ELMInstance,
    ELMIntersect,
    ELMInterval,
    ELMInValueSet,
    ELMIs,
    ELMIsFalse,
    ELMIsNull,
    ELMIsTrue,
    ELMLast,
    ELMLastPositionOf,
    ELMLength,
    ELMLess,
    ELMLessOrEqual,
    ELMLetClause,
    ELMList,
    # Literals
    ELMLiteral,
    ELMLn,
    ELMLog,
    ELMLower,
    ELMMatches,
    ELMMax,
    ELMMaxValue,
    ELMMedian,
    ELMMeets,
    ELMMeetsAfter,
    ELMMeetsBefore,
    # Misc
    ELMMessage,
    ELMMin,
    ELMMinValue,
    ELMMode,
    ELMModulo,
    ELMMultiply,
    ELMNaryExpression,
    ELMNegate,
    ELMNot,
    ELMNotEqual,
    ELMNow,
    ELMNull,
    ELMOr,
    ELMOverlaps,
    ELMOverlapsAfter,
    ELMOverlapsBefore,
    ELMParameterRef,
    ELMPointFrom,
    ELMPopulationStdDev,
    ELMPopulationVariance,
    ELMPositionOf,
    ELMPower,
    ELMPredecessor,
    ELMProduct,
    ELMProperIncludedIn,
    ELMProperIncludes,
    ELMProperty,
    ELMQuantity,
    ELMQuery,
    ELMQueryLetRef,
    ELMRatio,
    ELMRepeat,
    ELMReplaceMatches,
    # Clinical
    ELMRetrieve,
    ELMReturnClause,
    ELMRound,
    ELMSameAs,
    ELMSameOrAfter,
    ELMSameOrBefore,
    ELMSingletonFrom,
    ELMSize,
    ELMSortByItem,
    ELMSortClause,
    ELMSplit,
    # Interval operations
    ELMStart,
    ELMStarts,
    ELMStartsWith,
    ELMStdDev,
    ELMSubstring,
    ELMSubtract,
    ELMSuccessor,
    ELMSum,
    ELMTernaryExpression,
    ELMTime,
    ELMTimeFrom,
    ELMTimeOfDay,
    ELMTimes,
    ELMTimezoneOffsetFrom,
    ELMToBoolean,
    ELMToConcept,
    ELMToDate,
    ELMToDateTime,
    # Date/Time
    ELMToday,
    ELMToDecimal,
    ELMToInteger,
    ELMToList,
    ELMToLong,
    ELMToQuantity,
    ELMToString,
    ELMToTime,
    ELMTruncate,
    ELMTruncatedDivide,
    ELMTuple,
    ELMTupleElement,
    ELMUnaryExpression,
    # Set operations
    ELMUnion,
    ELMUpper,
    ELMValueSetRef,
    ELMVariance,
    ELMWidth,
    ELMWith,
    ELMWithout,
    ELMXor,
)
from fhirkit.engine.elm.models.library import (
    ELMCodeDef,
    ELMCodeSystem,
    ELMConceptDef,
    ELMContextDef,
    ELMDefinition,
    ELMFunctionDef,
    ELMIdentifier,
    ELMInclude,
    ELMLibrary,
    ELMOperandDef,
    ELMParameter,
    ELMStatements,
    ELMUsing,
    ELMValueSet,
)
from fhirkit.engine.elm.models.library import (
    ELMCodeRef as ELMLibraryCodeRef,
)
from fhirkit.engine.elm.models.library import (
    ELMCodeSystemRef as ELMLibraryCodeSystemRef,
)
from fhirkit.engine.elm.models.types import (
    AnyTypeSpecifier,
    ELMChoiceTypeSpecifier,
    ELMIntervalTypeSpecifier,
    ELMListTypeSpecifier,
    ELMNamedTypeSpecifier,
    ELMTupleElementDefinition,
    ELMTupleTypeSpecifier,
    ELMTypeSpecifier,
)

__all__ = [
    # Library
    "ELMLibrary",
    "ELMIdentifier",
    "ELMUsing",
    "ELMInclude",
    "ELMParameter",
    "ELMCodeSystem",
    "ELMValueSet",
    "ELMCodeDef",
    "ELMConceptDef",
    "ELMContextDef",
    "ELMDefinition",
    "ELMFunctionDef",
    "ELMOperandDef",
    "ELMStatements",
    "ELMLibraryCodeSystemRef",
    "ELMLibraryCodeRef",
    # Types
    "ELMTypeSpecifier",
    "ELMNamedTypeSpecifier",
    "ELMListTypeSpecifier",
    "ELMIntervalTypeSpecifier",
    "ELMTupleTypeSpecifier",
    "ELMTupleElementDefinition",
    "ELMChoiceTypeSpecifier",
    "AnyTypeSpecifier",
    # Expressions - Base
    "ELMExpression",
    "ELMUnaryExpression",
    "ELMBinaryExpression",
    "ELMTernaryExpression",
    "ELMNaryExpression",
    "ELMAggregateExpression",
    # Literals
    "ELMLiteral",
    "ELMNull",
    "ELMTupleElement",
    "ELMTuple",
    "ELMInstance",
    "ELMList",
    "ELMInterval",
    "ELMQuantity",
    "ELMRatio",
    "ELMCode",
    "ELMConcept",
    # Arithmetic
    "ELMAdd",
    "ELMSubtract",
    "ELMMultiply",
    "ELMDivide",
    "ELMTruncatedDivide",
    "ELMModulo",
    "ELMPower",
    "ELMNegate",
    "ELMAbs",
    "ELMCeiling",
    "ELMFloor",
    "ELMTruncate",
    "ELMRound",
    "ELMLn",
    "ELMLog",
    "ELMExp",
    "ELMSuccessor",
    "ELMPredecessor",
    "ELMMinValue",
    "ELMMaxValue",
    # Comparison
    "ELMEqual",
    "ELMNotEqual",
    "ELMEquivalent",
    "ELMLess",
    "ELMLessOrEqual",
    "ELMGreater",
    "ELMGreaterOrEqual",
    # Boolean
    "ELMAnd",
    "ELMOr",
    "ELMXor",
    "ELMNot",
    "ELMImplies",
    "ELMIsTrue",
    "ELMIsFalse",
    "ELMIsNull",
    # Control flow
    "ELMIf",
    "ELMCaseItem",
    "ELMCase",
    "ELMCoalesce",
    # String
    "ELMConcatenate",
    "ELMCombine",
    "ELMSplit",
    "ELMLength",
    "ELMUpper",
    "ELMLower",
    "ELMSubstring",
    "ELMStartsWith",
    "ELMEndsWith",
    "ELMMatches",
    "ELMReplaceMatches",
    "ELMIndexer",
    "ELMPositionOf",
    "ELMLastPositionOf",
    # Collections
    "ELMFirst",
    "ELMLast",
    "ELMIndexOf",
    "ELMContains",
    "ELMIn",
    "ELMIncludes",
    "ELMIncludedIn",
    "ELMProperIncludes",
    "ELMProperIncludedIn",
    "ELMDistinct",
    "ELMFlatten",
    "ELMExists",
    "ELMSingletonFrom",
    "ELMToList",
    # Aggregates
    "ELMCount",
    "ELMSum",
    "ELMAvg",
    "ELMMin",
    "ELMMax",
    "ELMMedian",
    "ELMMode",
    "ELMVariance",
    "ELMPopulationVariance",
    "ELMStdDev",
    "ELMPopulationStdDev",
    "ELMAllTrue",
    "ELMAnyTrue",
    "ELMProduct",
    "ELMGeometricMean",
    # Set operations
    "ELMUnion",
    "ELMIntersect",
    "ELMExcept",
    # References
    "ELMExpressionRef",
    "ELMFunctionRef",
    "ELMParameterRef",
    "ELMProperty",
    "ELMAliasRef",
    "ELMQueryLetRef",
    "ELMIdentifierRef",
    # Query
    "ELMAliasedQuerySource",
    "ELMLetClause",
    "ELMSortByItem",
    "ELMSortClause",
    "ELMReturnClause",
    "ELMAggregateClause",
    "ELMWith",
    "ELMWithout",
    "ELMQuery",
    "ELMForEach",
    "ELMRepeat",
    "ELMFilter",
    "ELMTimes",
    # Clinical
    "ELMRetrieve",
    "ELMCodeSystemRef",
    "ELMValueSetRef",
    "ELMCodeRef",
    "ELMConceptRef",
    "ELMInValueSet",
    "ELMInCodeSystem",
    "ELMCalculateAge",
    "ELMCalculateAgeAt",
    # Type operations
    "ELMAs",
    "ELMIs",
    "ELMToBoolean",
    "ELMToInteger",
    "ELMToLong",
    "ELMToDecimal",
    "ELMToString",
    "ELMToDateTime",
    "ELMToDate",
    "ELMToTime",
    "ELMToQuantity",
    "ELMToConcept",
    "ELMConvertsToBoolean",
    "ELMConvertsToInteger",
    "ELMConvertsToDecimal",
    "ELMConvertsToString",
    "ELMConvertsToDateTime",
    "ELMConvertsToDate",
    "ELMConvertsToTime",
    "ELMConvertsToQuantity",
    # Date/Time
    "ELMToday",
    "ELMNow",
    "ELMTimeOfDay",
    "ELMDate",
    "ELMDateTime",
    "ELMTime",
    "ELMDurationBetween",
    "ELMDifferenceBetween",
    "ELMDateFrom",
    "ELMTimeFrom",
    "ELMTimezoneOffsetFrom",
    "ELMDateTimeComponentFrom",
    "ELMSameAs",
    "ELMSameOrBefore",
    "ELMSameOrAfter",
    # Interval operations
    "ELMStart",
    "ELMEnd",
    "ELMWidth",
    "ELMSize",
    "ELMPointFrom",
    "ELMOverlaps",
    "ELMOverlapsBefore",
    "ELMOverlapsAfter",
    "ELMMeets",
    "ELMMeetsBefore",
    "ELMMeetsAfter",
    "ELMBefore",
    "ELMAfter",
    "ELMStarts",
    "ELMEnds",
    "ELMCollapse",
    "ELMExpand",
    # Misc
    "ELMMessage",
]
